/*
 * AUTO-GENERATED FILE. Do not edit by hand.
 *
 * Generator: emu-experiments/disasm-upgrade/tools/z80_meta_gen/gen_z80_meta.py
 * Source data:
 *   - entries.py (hard-coded tabulka tříd instrukcí)
 *   - mz800-knowledge/reference/agent/cpu/z80/06-flag-affection.md
 *     (kanonický zdroj flag effects, použit pro křížovou kontrolu)
 *
 * Pro regeneraci spusť:
 *   cd emu-experiments/disasm-upgrade/tools/z80_meta_gen
 *   python3 gen_z80_meta.py
 */

#include "libs/z80meta/z80_meta.h"
#include "libs/dasm-z80/z80_dasm.h"

#include <stddef.h>
#include <string.h>

/**
 * @brief Interní záznam tabulky metadat Z80 instrukcí.
 *
 * Klíč = (mnemonic, op1_type, op2_type) plus volitelný subtype pro
 * rozlišení variant se stejným typem operandu (např. LD A,I vs LD A,r).
 *
 * Subtype hodnota -1 znamená "any" (= bere libovolnou hodnotu daného typu).
 *
 * @invariant mnemonic ukazuje na statický string literal.
 * @invariant flags[8] obsahuje detail flag effects v pořadí
 *            S, Z, F5, H, F3, P/V, N, C (MSB → LSB).
 */
typedef struct {
    const char *mnemonic;        /**< Mnemonika instrukce (např. "ADD"). */
    z80_operand_type_t op1_type; /**< Typ prvního operandu. */
    z80_operand_type_t op2_type; /**< Typ druhého operandu. */
    int16_t op1_subtype;         /**< Konkrétní hodnota op1 (reg8, reg16),
                                      nebo -1 pro libovolnou. */
    int16_t op2_subtype;         /**< Konkrétní hodnota op2, -1 pro libovolnou. */
    z80_meta_t meta;             /**< Vlastní metadata (description + flags). */
} z80_meta_entry_t;


/**
 * @brief Tabulka metadat tříd instrukcí Z80.
 *
 * Pořadí má význam: konkrétní (subtype != -1) entries musí být
 * uvedeny **před** generickými, aby je lookup matchnul jako první
 * (viz z80_meta_table_lookup).
 */
static const z80_meta_entry_t z80_meta_table[] = {
    { "LD", Z80_OP_REG8, Z80_OP_REG8, -1, -1, { "LD r,r': r = r'", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "LD", Z80_OP_REG8, Z80_OP_IMM8, -1, -1, { "LD r,n: r = n", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "LD", Z80_OP_REG8, Z80_OP_MEM_REG16, -1, -1, { "LD r,(rr): r = (rr)", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "LD", Z80_OP_MEM_REG16, Z80_OP_REG8, -1, -1, { "LD (rr),r: (rr) = r", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "LD", Z80_OP_MEM_REG16, Z80_OP_IMM8, -1, -1, { "LD (HL),n: (HL) = n", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "LD", Z80_OP_REG8, Z80_OP_MEM_IX_D, -1, -1, { "LD r,(IX+d): r = (IX+d)", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "LD", Z80_OP_REG8, Z80_OP_MEM_IY_D, -1, -1, { "LD r,(IY+d): r = (IY+d)", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "LD", Z80_OP_MEM_IX_D, Z80_OP_REG8, -1, -1, { "LD (IX+d),r: (IX+d) = r", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "LD", Z80_OP_MEM_IY_D, Z80_OP_REG8, -1, -1, { "LD (IY+d),r: (IY+d) = r", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "LD", Z80_OP_MEM_IX_D, Z80_OP_IMM8, -1, -1, { "LD (IX+d),n: (IX+d) = n", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "LD", Z80_OP_MEM_IY_D, Z80_OP_IMM8, -1, -1, { "LD (IY+d),n: (IY+d) = n", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "LD", Z80_OP_REG8, Z80_OP_MEM_IMM16, -1, -1, { "LD A,(nn): A = (nn)", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "LD", Z80_OP_MEM_IMM16, Z80_OP_REG8, -1, -1, { "LD (nn),A: (nn) = A", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "LD", Z80_OP_REG8, Z80_OP_REG8, Z80_R8_A, Z80_R8_I, { "LD A,I: A=I, PV=IFF2", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_SPECIAL, Z80_FE_RESET, Z80_FE_UNAFFECTED} } },
    { "LD", Z80_OP_REG8, Z80_OP_REG8, Z80_R8_A, Z80_R8_R, { "LD A,R: A=R, PV=IFF2", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_SPECIAL, Z80_FE_RESET, Z80_FE_UNAFFECTED} } },
    { "LD", Z80_OP_REG8, Z80_OP_REG8, Z80_R8_I, Z80_R8_A, { "LD I,A: I = A", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "LD", Z80_OP_REG8, Z80_OP_REG8, Z80_R8_R, Z80_R8_A, { "LD R,A: R = A", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "LD", Z80_OP_REG16, Z80_OP_IMM16, -1, -1, { "LD rr,nn: rr = nn", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "LD", Z80_OP_REG16, Z80_OP_MEM_IMM16, -1, -1, { "LD rr,(nn): rr = (nn)", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "LD", Z80_OP_MEM_IMM16, Z80_OP_REG16, -1, -1, { "LD (nn),rr: (nn) = rr", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "LD", Z80_OP_REG16, Z80_OP_REG16, -1, -1, { "LD rr,rr': rr = rr'", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "PUSH", Z80_OP_REG16, Z80_OP_NONE, -1, -1, { "PUSH rr: stack <- rr", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "POP", Z80_OP_REG16, Z80_OP_NONE, -1, -1, { "POP rr: rr <- stack", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "EX", Z80_OP_REG16, Z80_OP_REG16, -1, -1, { "EX rr,rr': swap registers", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "EX", Z80_OP_MEM_REG16, Z80_OP_REG16, -1, -1, { "EX (SP),rr: swap (SP) <-> rr", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "EXX", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "EXX: swap BC/DE/HL <-> shadow", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "ADD", Z80_OP_REG8, Z80_OP_REG8, -1, -1, { "ADD A,r: A = A + r", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "ADD", Z80_OP_REG8, Z80_OP_IMM8, -1, -1, { "ADD A,n: A = A + n", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "ADD", Z80_OP_REG8, Z80_OP_MEM_REG16, -1, -1, { "ADD A,(HL): A = A + (HL)", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "ADD", Z80_OP_REG8, Z80_OP_MEM_IX_D, -1, -1, { "ADD A,(IX+d): A = A + (IX+d)", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "ADD", Z80_OP_REG8, Z80_OP_MEM_IY_D, -1, -1, { "ADD A,(IY+d): A = A + (IY+d)", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "ADC", Z80_OP_REG8, Z80_OP_REG8, -1, -1, { "ADC A,r: A = A + r + CF", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "ADC", Z80_OP_REG8, Z80_OP_IMM8, -1, -1, { "ADC A,n: A = A + n + CF", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "ADC", Z80_OP_REG8, Z80_OP_MEM_REG16, -1, -1, { "ADC A,(HL): A = A + (HL) + CF", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "ADC", Z80_OP_REG8, Z80_OP_MEM_IX_D, -1, -1, { "ADC A,(IX+d): A=A+(IX+d)+CF", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "ADC", Z80_OP_REG8, Z80_OP_MEM_IY_D, -1, -1, { "ADC A,(IY+d): A=A+(IY+d)+CF", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "SUB", Z80_OP_REG8, Z80_OP_NONE, -1, -1, { "SUB r: A = A - r", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_SET, Z80_FE_RESULT} } },
    { "SUB", Z80_OP_IMM8, Z80_OP_NONE, -1, -1, { "SUB n: A = A - n", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_SET, Z80_FE_RESULT} } },
    { "SUB", Z80_OP_MEM_REG16, Z80_OP_NONE, -1, -1, { "SUB (HL): A = A - (HL)", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_SET, Z80_FE_RESULT} } },
    { "SUB", Z80_OP_MEM_IX_D, Z80_OP_NONE, -1, -1, { "SUB (IX+d): A = A - (IX+d)", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_SET, Z80_FE_RESULT} } },
    { "SUB", Z80_OP_MEM_IY_D, Z80_OP_NONE, -1, -1, { "SUB (IY+d): A = A - (IY+d)", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_SET, Z80_FE_RESULT} } },
    { "SBC", Z80_OP_REG8, Z80_OP_REG8, -1, -1, { "SBC A,r: A = A - r - CF", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_SET, Z80_FE_RESULT} } },
    { "SBC", Z80_OP_REG8, Z80_OP_IMM8, -1, -1, { "SBC A,n: A = A - n - CF", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_SET, Z80_FE_RESULT} } },
    { "SBC", Z80_OP_REG8, Z80_OP_MEM_REG16, -1, -1, { "SBC A,(HL): A = A - (HL) - CF", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_SET, Z80_FE_RESULT} } },
    { "SBC", Z80_OP_REG8, Z80_OP_MEM_IX_D, -1, -1, { "SBC A,(IX+d): A=A-(IX+d)-CF", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_SET, Z80_FE_RESULT} } },
    { "SBC", Z80_OP_REG8, Z80_OP_MEM_IY_D, -1, -1, { "SBC A,(IY+d): A=A-(IY+d)-CF", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_SET, Z80_FE_RESULT} } },
    { "CP", Z80_OP_REG8, Z80_OP_NONE, -1, -1, { "CP r: compare A with r", {Z80_FE_RESULT, Z80_FE_SPECIAL, Z80_FE_RESULT, Z80_FE_SPECIAL, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_SET, Z80_FE_RESULT} } },
    { "CP", Z80_OP_IMM8, Z80_OP_NONE, -1, -1, { "CP n: compare A with n", {Z80_FE_RESULT, Z80_FE_SPECIAL, Z80_FE_RESULT, Z80_FE_SPECIAL, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_SET, Z80_FE_RESULT} } },
    { "CP", Z80_OP_MEM_REG16, Z80_OP_NONE, -1, -1, { "CP (HL): compare A with (HL)", {Z80_FE_RESULT, Z80_FE_SPECIAL, Z80_FE_RESULT, Z80_FE_SPECIAL, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_SET, Z80_FE_RESULT} } },
    { "CP", Z80_OP_MEM_IX_D, Z80_OP_NONE, -1, -1, { "CP (IX+d): compare A with (IX+d)", {Z80_FE_RESULT, Z80_FE_SPECIAL, Z80_FE_RESULT, Z80_FE_SPECIAL, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_SET, Z80_FE_RESULT} } },
    { "CP", Z80_OP_MEM_IY_D, Z80_OP_NONE, -1, -1, { "CP (IY+d): compare A with (IY+d)", {Z80_FE_RESULT, Z80_FE_SPECIAL, Z80_FE_RESULT, Z80_FE_SPECIAL, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_SET, Z80_FE_RESULT} } },
    { "INC", Z80_OP_REG8, Z80_OP_NONE, -1, -1, { "INC r: r = r + 1", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_RESET, Z80_FE_UNAFFECTED} } },
    { "INC", Z80_OP_MEM_REG16, Z80_OP_NONE, -1, -1, { "INC (HL): (HL) = (HL) + 1", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_RESET, Z80_FE_UNAFFECTED} } },
    { "INC", Z80_OP_MEM_IX_D, Z80_OP_NONE, -1, -1, { "INC (IX+d): (IX+d) = (IX+d)+1", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_RESET, Z80_FE_UNAFFECTED} } },
    { "INC", Z80_OP_MEM_IY_D, Z80_OP_NONE, -1, -1, { "INC (IY+d): (IY+d) = (IY+d)+1", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_RESET, Z80_FE_UNAFFECTED} } },
    { "DEC", Z80_OP_REG8, Z80_OP_NONE, -1, -1, { "DEC r: r = r - 1", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_SET, Z80_FE_UNAFFECTED} } },
    { "DEC", Z80_OP_MEM_REG16, Z80_OP_NONE, -1, -1, { "DEC (HL): (HL) = (HL) - 1", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_SET, Z80_FE_UNAFFECTED} } },
    { "DEC", Z80_OP_MEM_IX_D, Z80_OP_NONE, -1, -1, { "DEC (IX+d): (IX+d) = (IX+d)-1", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_SET, Z80_FE_UNAFFECTED} } },
    { "DEC", Z80_OP_MEM_IY_D, Z80_OP_NONE, -1, -1, { "DEC (IY+d): (IY+d) = (IY+d)-1", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_SET, Z80_FE_UNAFFECTED} } },
    { "INC", Z80_OP_REG16, Z80_OP_NONE, -1, -1, { "INC rr: rr = rr + 1", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "DEC", Z80_OP_REG16, Z80_OP_NONE, -1, -1, { "DEC rr: rr = rr - 1", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "ADD", Z80_OP_REG16, Z80_OP_REG16, -1, -1, { "ADD ss,rr: ss = ss + rr", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_UNAFFECTED, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "ADC", Z80_OP_REG16, Z80_OP_REG16, -1, -1, { "ADC HL,rr: HL = HL + rr + CF", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "SBC", Z80_OP_REG16, Z80_OP_REG16, -1, -1, { "SBC HL,rr: HL = HL - rr - CF", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_SET, Z80_FE_RESULT} } },
    { "DAA", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "DAA: BCD adjust A", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_UNAFFECTED, Z80_FE_RESULT} } },
    { "CPL", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "CPL: A = NOT A", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_RESULT, Z80_FE_SET, Z80_FE_RESULT, Z80_FE_UNAFFECTED, Z80_FE_SET, Z80_FE_UNAFFECTED} } },
    { "NEG", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "NEG: A = 0 - A", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_OVERFLOW, Z80_FE_SET, Z80_FE_RESULT} } },
    { "CCF", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "CCF: CF = NOT CF", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_RESULT, Z80_FE_SPECIAL, Z80_FE_RESULT, Z80_FE_UNAFFECTED, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "SCF", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "SCF: CF = 1", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_UNAFFECTED, Z80_FE_RESET, Z80_FE_SET} } },
    { "AND", Z80_OP_REG8, Z80_OP_NONE, -1, -1, { "AND r: A = A AND r", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_SET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESET} } },
    { "AND", Z80_OP_IMM8, Z80_OP_NONE, -1, -1, { "AND n: A = A AND n", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_SET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESET} } },
    { "AND", Z80_OP_MEM_REG16, Z80_OP_NONE, -1, -1, { "AND (HL): A = A AND (HL)", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_SET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESET} } },
    { "AND", Z80_OP_MEM_IX_D, Z80_OP_NONE, -1, -1, { "AND (IX+d): A = A AND (IX+d)", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_SET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESET} } },
    { "AND", Z80_OP_MEM_IY_D, Z80_OP_NONE, -1, -1, { "AND (IY+d): A = A AND (IY+d)", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_SET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESET} } },
    { "OR", Z80_OP_REG8, Z80_OP_NONE, -1, -1, { "OR r: A = A OR r", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESET} } },
    { "OR", Z80_OP_IMM8, Z80_OP_NONE, -1, -1, { "OR n: A = A OR n", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESET} } },
    { "OR", Z80_OP_MEM_REG16, Z80_OP_NONE, -1, -1, { "OR (HL): A = A OR (HL)", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESET} } },
    { "OR", Z80_OP_MEM_IX_D, Z80_OP_NONE, -1, -1, { "OR (IX+d): A = A OR (IX+d)", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESET} } },
    { "OR", Z80_OP_MEM_IY_D, Z80_OP_NONE, -1, -1, { "OR (IY+d): A = A OR (IY+d)", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESET} } },
    { "XOR", Z80_OP_REG8, Z80_OP_NONE, -1, -1, { "XOR r: A = A XOR r", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESET} } },
    { "XOR", Z80_OP_IMM8, Z80_OP_NONE, -1, -1, { "XOR n: A = A XOR n", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESET} } },
    { "XOR", Z80_OP_MEM_REG16, Z80_OP_NONE, -1, -1, { "XOR (HL): A = A XOR (HL)", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESET} } },
    { "XOR", Z80_OP_MEM_IX_D, Z80_OP_NONE, -1, -1, { "XOR (IX+d): A = A XOR (IX+d)", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESET} } },
    { "XOR", Z80_OP_MEM_IY_D, Z80_OP_NONE, -1, -1, { "XOR (IY+d): A = A XOR (IY+d)", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESET} } },
    { "BIT", Z80_OP_BIT_INDEX, Z80_OP_REG8, -1, -1, { "BIT n,r: test bit n of r", {Z80_FE_SPECIAL, Z80_FE_RESULT, Z80_FE_SPECIAL, Z80_FE_SET, Z80_FE_SPECIAL, Z80_FE_SPECIAL, Z80_FE_RESET, Z80_FE_UNAFFECTED} } },
    { "BIT", Z80_OP_BIT_INDEX, Z80_OP_MEM_REG16, -1, -1, { "BIT n,(HL): test bit n of (HL)", {Z80_FE_SPECIAL, Z80_FE_RESULT, Z80_FE_SPECIAL, Z80_FE_SET, Z80_FE_SPECIAL, Z80_FE_SPECIAL, Z80_FE_RESET, Z80_FE_UNAFFECTED} } },
    { "BIT", Z80_OP_BIT_INDEX, Z80_OP_MEM_IX_D, -1, -1, { "BIT n,(IX+d): test bit n", {Z80_FE_SPECIAL, Z80_FE_RESULT, Z80_FE_SPECIAL, Z80_FE_SET, Z80_FE_SPECIAL, Z80_FE_SPECIAL, Z80_FE_RESET, Z80_FE_UNAFFECTED} } },
    { "BIT", Z80_OP_BIT_INDEX, Z80_OP_MEM_IY_D, -1, -1, { "BIT n,(IY+d): test bit n", {Z80_FE_SPECIAL, Z80_FE_RESULT, Z80_FE_SPECIAL, Z80_FE_SET, Z80_FE_SPECIAL, Z80_FE_SPECIAL, Z80_FE_RESET, Z80_FE_UNAFFECTED} } },
    { "SET", Z80_OP_BIT_INDEX, Z80_OP_REG8, -1, -1, { "SET n,r: r |= (1 << n)", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "SET", Z80_OP_BIT_INDEX, Z80_OP_MEM_REG16, -1, -1, { "SET n,(HL): set bit n", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "SET", Z80_OP_BIT_INDEX, Z80_OP_MEM_IX_D, -1, -1, { "SET n,(IX+d): set bit n", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "SET", Z80_OP_BIT_INDEX, Z80_OP_MEM_IY_D, -1, -1, { "SET n,(IY+d): set bit n", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "RES", Z80_OP_BIT_INDEX, Z80_OP_REG8, -1, -1, { "RES n,r: r &= ~(1 << n)", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "RES", Z80_OP_BIT_INDEX, Z80_OP_MEM_REG16, -1, -1, { "RES n,(HL): reset bit n", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "RES", Z80_OP_BIT_INDEX, Z80_OP_MEM_IX_D, -1, -1, { "RES n,(IX+d): reset bit n", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "RES", Z80_OP_BIT_INDEX, Z80_OP_MEM_IY_D, -1, -1, { "RES n,(IY+d): reset bit n", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "RLCA", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "RLCA: rotate A left with CF", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_UNAFFECTED, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "RLA", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "RLA: rotate A left through CF", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_UNAFFECTED, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "RRCA", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "RRCA: rotate A right with CF", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_UNAFFECTED, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "RRA", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "RRA: rotate A right through CF", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_UNAFFECTED, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "RLC", Z80_OP_REG8, Z80_OP_NONE, -1, -1, { "RLC r: rotate r left with CF", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "RLC", Z80_OP_MEM_REG16, Z80_OP_NONE, -1, -1, { "RLC (HL): rotate (HL) left", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "RLC", Z80_OP_MEM_IX_D, Z80_OP_NONE, -1, -1, { "RLC (IX+d): rotate left", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "RLC", Z80_OP_MEM_IY_D, Z80_OP_NONE, -1, -1, { "RLC (IY+d): rotate left", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "RL", Z80_OP_REG8, Z80_OP_NONE, -1, -1, { "RL r: rotate r left through CF", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "RL", Z80_OP_MEM_REG16, Z80_OP_NONE, -1, -1, { "RL (HL): rotate through CF", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "RL", Z80_OP_MEM_IX_D, Z80_OP_NONE, -1, -1, { "RL (IX+d): rotate through CF", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "RL", Z80_OP_MEM_IY_D, Z80_OP_NONE, -1, -1, { "RL (IY+d): rotate through CF", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "RRC", Z80_OP_REG8, Z80_OP_NONE, -1, -1, { "RRC r: rotate r right with CF", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "RRC", Z80_OP_MEM_REG16, Z80_OP_NONE, -1, -1, { "RRC (HL): rotate right", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "RRC", Z80_OP_MEM_IX_D, Z80_OP_NONE, -1, -1, { "RRC (IX+d): rotate right", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "RRC", Z80_OP_MEM_IY_D, Z80_OP_NONE, -1, -1, { "RRC (IY+d): rotate right", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "RR", Z80_OP_REG8, Z80_OP_NONE, -1, -1, { "RR r: rotate r right through CF", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "RR", Z80_OP_MEM_REG16, Z80_OP_NONE, -1, -1, { "RR (HL): rotate through CF", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "RR", Z80_OP_MEM_IX_D, Z80_OP_NONE, -1, -1, { "RR (IX+d): rotate through CF", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "RR", Z80_OP_MEM_IY_D, Z80_OP_NONE, -1, -1, { "RR (IY+d): rotate through CF", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "SLA", Z80_OP_REG8, Z80_OP_NONE, -1, -1, { "SLA r: shift left arith.", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "SLA", Z80_OP_MEM_REG16, Z80_OP_NONE, -1, -1, { "SLA (HL): shift left arith.", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "SLA", Z80_OP_MEM_IX_D, Z80_OP_NONE, -1, -1, { "SLA (IX+d): shift left", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "SLA", Z80_OP_MEM_IY_D, Z80_OP_NONE, -1, -1, { "SLA (IY+d): shift left", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "SRA", Z80_OP_REG8, Z80_OP_NONE, -1, -1, { "SRA r: shift right arith.", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "SRA", Z80_OP_MEM_REG16, Z80_OP_NONE, -1, -1, { "SRA (HL): shift right arith.", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "SRA", Z80_OP_MEM_IX_D, Z80_OP_NONE, -1, -1, { "SRA (IX+d): shift right", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "SRA", Z80_OP_MEM_IY_D, Z80_OP_NONE, -1, -1, { "SRA (IY+d): shift right", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "SLL", Z80_OP_REG8, Z80_OP_NONE, -1, -1, { "SLL r: shift left logical (und)", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "SLL", Z80_OP_MEM_REG16, Z80_OP_NONE, -1, -1, { "SLL (HL): shift left log.", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "SLL", Z80_OP_MEM_IX_D, Z80_OP_NONE, -1, -1, { "SLL (IX+d): shift left log.", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "SLL", Z80_OP_MEM_IY_D, Z80_OP_NONE, -1, -1, { "SLL (IY+d): shift left log.", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "SRL", Z80_OP_REG8, Z80_OP_NONE, -1, -1, { "SRL r: shift right log.", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "SRL", Z80_OP_MEM_REG16, Z80_OP_NONE, -1, -1, { "SRL (HL): shift right log.", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "SRL", Z80_OP_MEM_IX_D, Z80_OP_NONE, -1, -1, { "SRL (IX+d): shift right log.", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "SRL", Z80_OP_MEM_IY_D, Z80_OP_NONE, -1, -1, { "SRL (IY+d): shift right log.", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_RESULT} } },
    { "RLD", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "RLD: BCD rotate (HL)/A left", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_UNAFFECTED} } },
    { "RRD", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "RRD: BCD rotate (HL)/A right", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_UNAFFECTED} } },
    { "JP", Z80_OP_IMM16, Z80_OP_NONE, -1, -1, { "JP nn: PC = nn", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "JP", Z80_OP_MEM_REG16, Z80_OP_NONE, -1, -1, { "JP (rr): PC = rr (no indirect)", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "JP", Z80_OP_CONDITION, Z80_OP_IMM16, -1, -1, { "JP cc,nn: jump if cc", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "JR", Z80_OP_REL8, Z80_OP_NONE, -1, -1, { "JR e: relative jump", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "JR", Z80_OP_CONDITION, Z80_OP_REL8, -1, -1, { "JR cc,e: relative jump if cc", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "DJNZ", Z80_OP_REL8, Z80_OP_NONE, -1, -1, { "DJNZ e: B--, jump if B!=0", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "CALL", Z80_OP_IMM16, Z80_OP_NONE, -1, -1, { "CALL nn: call subroutine", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "CALL", Z80_OP_CONDITION, Z80_OP_IMM16, -1, -1, { "CALL cc,nn: call if cc", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "RET", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "RET: return from call", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "RET", Z80_OP_CONDITION, Z80_OP_NONE, -1, -1, { "RET cc: return if cc", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "RETI", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "RETI: return from interrupt", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "RETN", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "RETN: return from NMI", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "RST", Z80_OP_RST_VEC, Z80_OP_NONE, -1, -1, { "RST p: call routine at p", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "LDI", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "LDI: (DE)=(HL),HL+,DE+,BC-", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_SPECIAL, Z80_FE_RESET, Z80_FE_SPECIAL, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_UNAFFECTED} } },
    { "LDIR", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "LDIR: repeat LDI while BC>0", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_SPECIAL, Z80_FE_RESET, Z80_FE_SPECIAL, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_UNAFFECTED} } },
    { "LDD", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "LDD: (DE)=(HL),HL-,DE-,BC-", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_SPECIAL, Z80_FE_RESET, Z80_FE_SPECIAL, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_UNAFFECTED} } },
    { "LDDR", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "LDDR: repeat LDD while BC>0", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_SPECIAL, Z80_FE_RESET, Z80_FE_SPECIAL, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_UNAFFECTED} } },
    { "CPI", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "CPI: cmp A with (HL),HL+,BC-", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_SPECIAL, Z80_FE_RESULT, Z80_FE_SPECIAL, Z80_FE_RESULT, Z80_FE_SET, Z80_FE_UNAFFECTED} } },
    { "CPIR", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "CPIR: repeat CPI while BC>0/Z", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_SPECIAL, Z80_FE_RESULT, Z80_FE_SPECIAL, Z80_FE_RESULT, Z80_FE_SET, Z80_FE_UNAFFECTED} } },
    { "CPD", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "CPD: cmp A with (HL),HL-,BC-", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_SPECIAL, Z80_FE_RESULT, Z80_FE_SPECIAL, Z80_FE_RESULT, Z80_FE_SET, Z80_FE_UNAFFECTED} } },
    { "CPDR", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "CPDR: repeat CPD while BC>0/Z", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_SPECIAL, Z80_FE_RESULT, Z80_FE_SPECIAL, Z80_FE_RESULT, Z80_FE_SET, Z80_FE_UNAFFECTED} } },
    { "INI", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "INI: (HL)=IN(C),HL+,B-", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_UNDEFINED, Z80_FE_RESULT, Z80_FE_UNDEFINED, Z80_FE_UNDEFINED, Z80_FE_UNDEFINED} } },
    { "INIR", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "INIR: repeat INI while B>0", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_UNDEFINED, Z80_FE_RESULT, Z80_FE_UNDEFINED, Z80_FE_UNDEFINED, Z80_FE_UNDEFINED} } },
    { "IND", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "IND: (HL)=IN(C),HL-,B-", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_UNDEFINED, Z80_FE_RESULT, Z80_FE_UNDEFINED, Z80_FE_UNDEFINED, Z80_FE_UNDEFINED} } },
    { "INDR", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "INDR: repeat IND while B>0", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_UNDEFINED, Z80_FE_RESULT, Z80_FE_UNDEFINED, Z80_FE_UNDEFINED, Z80_FE_UNDEFINED} } },
    { "OUTI", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "OUTI: OUT(C)=(HL),HL+,B-", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_UNDEFINED, Z80_FE_RESULT, Z80_FE_UNDEFINED, Z80_FE_UNDEFINED, Z80_FE_UNDEFINED} } },
    { "OTIR", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "OTIR: repeat OUTI while B>0", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_UNDEFINED, Z80_FE_RESULT, Z80_FE_UNDEFINED, Z80_FE_UNDEFINED, Z80_FE_UNDEFINED} } },
    { "OUTD", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "OUTD: OUT(C)=(HL),HL-,B-", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_UNDEFINED, Z80_FE_RESULT, Z80_FE_UNDEFINED, Z80_FE_UNDEFINED, Z80_FE_UNDEFINED} } },
    { "OTDR", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "OTDR: repeat OUTD while B>0", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_UNDEFINED, Z80_FE_RESULT, Z80_FE_UNDEFINED, Z80_FE_UNDEFINED, Z80_FE_UNDEFINED} } },
    { "IN", Z80_OP_REG8, Z80_OP_MEM_IMM8, -1, -1, { "IN A,(n): A = port[n]", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "IN", Z80_OP_REG8, Z80_OP_MEM_REG16, -1, -1, { "IN r,(C): r = port[BC]", {Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESULT, Z80_FE_RESET, Z80_FE_RESULT, Z80_FE_PARITY, Z80_FE_RESET, Z80_FE_UNAFFECTED} } },
    { "OUT", Z80_OP_MEM_IMM8, Z80_OP_REG8, -1, -1, { "OUT (n),A: port[n] = A", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "OUT", Z80_OP_MEM_REG16, Z80_OP_REG8, -1, -1, { "OUT (C),r: port[BC] = r", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "OUT", Z80_OP_MEM_REG16, Z80_OP_IMM8, -1, -1, { "OUT (C),0: port[BC] = 0 (und)", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "NOP", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "NOP: no operation", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "HALT", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "HALT: halt until interrupt", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "DI", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "DI: disable interrupts", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "EI", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "EI: enable interrupts", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "IM", Z80_OP_IMM8, Z80_OP_NONE, -1, -1, { "IM n: set interrupt mode", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
    { "NOP*", Z80_OP_NONE, Z80_OP_NONE, -1, -1, { "NOP*: invalid sequence", {Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED, Z80_FE_UNAFFECTED} } },
};

/**
 * @brief Velikost tabulky z80_meta_table v počtu záznamů.
 */
const size_t z80_meta_table_size =
    sizeof(z80_meta_table) / sizeof(z80_meta_table[0]);

/**
 * @brief Pomocná funkce pro lookup - používá ji z80_meta.c.
 *
 * Vrací NULL, pokud žádná entry neodpovídá.
 *
 * Algoritmus: prochází tabulku v pořadí, vrací první match, který:
 *   1. Souhlasí na (mnemonic, op1_type, op2_type)
 *   2. A souhlasí na subtype (= konkrétní hodnota nebo -1 wildcard)
 *
 * Konkrétní subtype má přednost před wildcard, protože speciální entries
 * (např. LD A,I) jsou v tabulce *před* obecnou (LD r,r').
 */
const z80_meta_t *z80_meta_table_lookup(
    const char *mnemonic,
    z80_operand_type_t op1_type, z80_operand_type_t op2_type,
    int op1_subtype_val, int op2_subtype_val)
{
    if (mnemonic == NULL) {
        return NULL;
    }
    /* Dvouprůchodový lookup:
     *  1. nejprve hledáme exact match (vč. subtype),
     *  2. potom fallback na wildcard subtype.
     * To zajistí, že LD A,I (subtype=I) má přednost před generic LD r,r'
     * (subtype=-1) i když by se obecná entry vešla také.
     */
    for (int pass = 0; pass < 2; pass++) {
        for (size_t i = 0; i < z80_meta_table_size; i++) {
            const z80_meta_entry_t *e = &z80_meta_table[i];
            if (e->op1_type != op1_type || e->op2_type != op2_type) {
                continue;
            }
            /* Mnemonika - statický string z dasm-z80 (sdílený buffer),
             * proto strcmp. */
            if (strcmp(e->mnemonic, mnemonic) != 0) {
                continue;
            }
            if (pass == 0) {
                /* První pass: hledáme entry se specifikovaným subtype,
                 * který sedí. Wildcardy (-1) povolíme, ale aspoň jeden
                 * z nich musí být specifický a sedět na vstupu. */
                int s1_ok = (e->op1_subtype < 0) ||
                            (e->op1_subtype == op1_subtype_val);
                int s2_ok = (e->op2_subtype < 0) ||
                            (e->op2_subtype == op2_subtype_val);
                int has_specific = (e->op1_subtype >= 0) ||
                                   (e->op2_subtype >= 0);
                if (s1_ok && s2_ok && has_specific) {
                    return &e->meta;
                }
            } else {
                /* Druhá pass: jen entries kde oba subtypes jsou wildcard. */
                if (e->op1_subtype < 0 && e->op2_subtype < 0) {
                    return &e->meta;
                }
            }
        }
    }
    /* Vstupy nepoužité proměnné: subtype hodnoty pro op1/op2 jsou v algoritmu
     * pokryty výše; následující voidy jsou jen na potlačení -Wunused-parameter
     * v případě, že by funkce byla zavolána s argumenty které nikam dál
     * neputují. */
    (void)op1_subtype_val;
    (void)op2_subtype_val;
    return NULL;
}

